### PR TITLE
Retain application focus on render

### PR DESCRIPTION
**Pull request by jongold**
To @mathieudutour @darknoon,
`sketchtool run` always brings Sketch to the foreground - super annoying because it takes focus from your editor.

Turns out it's not that hard to do ~= what `sketchtool run` was doing with raw CocoaScript - I extracted it out to [run-sketch-plugin](https://github.com/jongold/run-sketch-plugin).

Any downsides to this approach? I didn't want to wait for Sketch to patch sketchtool

### CODE REVIEW

**Comment by mathieudutour** [comment]
one downside is that `runPluginCommandWithIdentifier:fromBundleAtURL: is deprecated, use runPluginCommandWithIdentifier:fromBundleAtURL:context: instead`

But I guess removing the ugly hack I've done to handle the different errors and not bringing sketch to the foreground is worth it

Can you fix the lint errors?

**Comment by mathieudutour** [comment]
published in `skpm@0.9.5`

**Comment by jongold** [comment]
@mathieudutour 
> one downside is that runPluginCommandWithIdentifier:fromBundleAtURL: is deprecated, use runPluginCommandWithIdentifier:fromBundleAtURL:context: instead

I figure we can fix that next. I tried changing it to use runPluginCommandWithIdentifier:fromBundleAtURL:context but it kept crashing - will investigate more.

@bomberstudios any chance we could have insight on when `runPluginCommandWithIdentifier:fromBundleAtURL` will break? I'll try to get it done by Sketch 44…

**Comment by bomberstudios** [comment]
Ping here, SketchTool 45 added a `--without-activating` option so maybe you want to re-add it to skpm or run-sketch-plugin to replace coscript.

**Comment by mathieudutour** [comment]
done here: https://github.com/skpm/skpm/pull/48 😄

**Comment by bomberstudios** [comment]
Awesome 👏👏👏

**Pull request merged**
