### PR TITLE
switch from rollup to webpack

### LINKED ISSUE #26: Can't use `require` method for importing modules
This is likely an issue with my own babel setup, but when using an external npm module (in this case [xml2js](#)), I'm getting the following error:

```
<Error>: ReferenceError: Can't find variable: require.
	Plugin “[Plugin Name]”, line 47:
	» var Util = _interopDefault(require('util'));
2017-04-06 15:57:02.173 Sketch[15619:8424183] Exception: {
    column = 35;
    line = 47;
}
```

This same error happens any time I use a module that uses the `require` method of importing modules. Here's my `.babelrc`:

```
{
  presets: [
    ["es2015", {modules: false}],
    "react",
  ],
  plugins: [
    "external-helpers",
    "transform-react-jsx",
  ],
}
```

I imagine I'm missing something obvious here... the `es2015` preset should do the conversion, shouldn't it?

Thanks.

### LINKED ISSUE #27: Speed up builds
Added `rollup-plugin-progress` to compare compilation times between rollup & webpack on the simple `react-sketchapp` examples — feels like rollup is significantly slower the webpack 

### skpm
**initial build** ~3500ms
**incremental builds w/ watch** ~1500ms
**incremental builds w/ watch, + disabling `treeshake`** ~1000ms

### webpack
**initial build** ~3500ms
**incremental builds** ~60ms

Is there a bug in the skpm config? Is there a better `watch` we can use? Should we disable treeshake?

### PR DESCRIPTION
**Pull request by mathieudutour**
@jongold I actually did have a bit of time. Didn't have time to really test it tho

fix #27, fix #26

### CODE REVIEW

**Comment by jongold** [comment]
dude this is awesome, amazing work and super fast turnaround. it's _way_ faster with react-sketchapp, and massively simplifies our documentation :)

I added some suggested tweaks to #29 if you'd like 🙏

**Comment by mathieudutour** [comment]
hum actually I'm not sure about the preset anymore: if you define a preset in the `babel-loader` options, the `.babelrc` is ignored

**Comment by jongold** [comment]
Ahhhh you're totally right. Hmm, is there a way around it? Not a big deal
if that's the only setup we have to do :)

jon.gold
628.228.1152

**Comment by mathieudutour** [comment]
maybe "calling" the preset and deconstructing it recursively until we have only plugins. But that doesn't seem nice

**Comment by mathieudutour** [comment]
or checking if there is a `.babelrc` and if so, not put the preset. That seems nicer

**Comment by jongold** [comment]
ok gimme a minute I'll try it

jon.gold
628.228.1152

**Comment by mathieudutour** [comment]
published in `skpm@0.8.0`

**Pull request merged**
